<?xml version="1.0" encoding="utf-8"?><Database Name="Flex" Class="FlexDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=38.192.14.25,49170;Initial Catalog=Flex;Persist Security Info=True;User ID=sa" SettingsObjectName="Flex.Database.Properties.Settings" SettingsPropertyName="FlexConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DB_ChildOrderings" Member="DB_ChildOrderings">
    <Type Name="DB_ChildOrdering">
      <Column Name="Parent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Child_Before" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Child_After" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DB_NounPhrases" Member="DB_NounPhrases">
    <Type Name="DB_NounPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdjectiveOrdering" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Elided" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Possessive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pronominal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_AdjectivePhrases" Member="DB_AdjectivePhrases">
    <Type Name="DB_AdjectivePhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_AdverbPhrases" Member="DB_AdverbPhrases">
    <Type Name="DB_AdverbPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_WeightedWords" Member="DB_WeightedWords">
    <Type Name="DB_WeightedWord">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordElement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DB_PrepositionalPhrases" Member="DB_PrepositionalPhrases">
    <Type Name="DB_PrepositionalPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Nouns" Member="DB_Nouns">
    <Type Name="DB_Noun">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Verbs" Member="DB_Verbs">
    <Type Name="DB_Verb">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Adjectives" Member="DB_Adjectives">
    <Type Name="DB_Adjective">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Adverbs" Member="DB_Adverbs">
    <Type Name="DB_Adverb">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Prepositions" Member="DB_Prepositions">
    <Type Name="DB_Preposition">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Conjunctions" Member="DB_Conjunctions">
    <Type Name="DB_Conjunction">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Determiners" Member="DB_Determiners">
    <Type Name="DB_Determiner">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_CardinalNumbers" Member="DB_CardinalNumbers">
    <Type Name="DB_CardinalNumber">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Modals" Member="DB_Modals">
    <Type Name="DB_Modal">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Particles" Member="DB_Particles">
    <Type Name="DB_Particle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Pronouns" Member="DB_Pronouns">
    <Type Name="DB_Pronoun">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PronounCase" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Elements" Member="DB_Elements">
    <Type Name="DB_Element">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ElementType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="FormsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Words" Member="DB_Words">
    <Type Name="DB_Word">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DefaultWeightedWord" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DefaultForm" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="FormsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Parents" Member="DB_Parents">
    <Type Name="DB_Parent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DefaultRealization" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FormsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LayerWords" Member="LayerWords">
    <Type Name="LayerWord">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WordType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DefaultWeightedWord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerParents" Member="LayerParents">
    <Type Name="LayerParent">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="DefaultRealization" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerPhrases" Member="LayerPhrases">
    <Type Name="LayerPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerNounPhrases" Member="LayerNounPhrases">
    <Type Name="LayerNounPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdjectiveOrdering" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Elided" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Possessive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pronominal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerAdjectivePhrases" Member="LayerAdjectivePhrases">
    <Type Name="LayerAdjectivePhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerAdverbPhrases" Member="LayerAdverbPhrases">
    <Type Name="LayerAdverbPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerPronouns" Member="LayerPronouns">
    <Type Name="LayerPronoun">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PronounCase" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerVerbPhrases" Member="LayerVerbPhrases">
    <Type Name="LayerVerbPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Form" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LayerClauses" Member="LayerClauses">
    <Type Name="LayerClause">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Complementizer" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Form" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InterrogativeType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_Clauses" Member="DB_Clauses">
    <Type Name="DB_Clause">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Complementizer" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Form" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InterrogativeType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_VerbPhrases" Member="DB_VerbPhrases">
    <Type Name="DB_VerbPhrase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Form" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DB_ParentChildRelations" Member="DB_ParentChildRelations">
    <Type Name="DB_ParentChildRelation">
      <Column Name="Parent" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Child" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Role" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SynsetToElementBindings" Member="SynsetToElementBindings">
    <Type Name="SynsetToElementBinding">
      <Column Name="SynsetID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ElementID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UnifiedNodes" Member="UnifiedNodes">
    <Type Name="UnifiedNode" Id="ID1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Role" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Weight" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ElementType" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="WordType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DefaultWeightedWord" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExpletiveSubject" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Proper" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Inflection" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Canned" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PronounCase" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Pronoun_Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Pronoun_Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Pronoun_Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="ParentType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="C_AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_Complementizer" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="C_Form" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C_InterrogativeType" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="C_Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="C_Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="C_Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="C_Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="DiscourseFunction" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="Appositive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NP_AdjectiveOrdering" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NP_Elided" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NP_Number" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NP_Gender" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NP_Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="NP_Possessive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NP_Pronominal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_AggregateAuxiliary" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_Form" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="VP_Modal" Type="System.String" DbType="VarChar(24)" CanBeNull="true" />
      <Column Name="VP_Negated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_Passive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_Perfect" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_Person" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="VP_Progressive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_SuppressGenitiveInGerund" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_SuppressedComplementizer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VP_Tense" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="AdjP_Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdjP_Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdvP_Comparative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdvP_Superlative" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetWeightedWordsForTree" Method="GetWeightedWordsForTree" IsComposable="true">
    <Parameter Name="RootID" Parameter="rootID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetWeightedWordsForTreeResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WordElement" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetChildOrderingsForTree" Method="GetChildOrderingsForTree" IsComposable="true">
    <Parameter Name="RootID" Parameter="rootID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetChildOrderingsForTreeResult">
      <Column Name="Parent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Child_Before" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Child_After" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetSynsetBindingsForTree" Method="GetSynsetBindingsForTree" IsComposable="true">
    <Parameter Name="RootID" Parameter="rootID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetSynsetBindingsForTreeResult">
      <Column Name="ElementID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SynsetID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetNodesForTree" Method="GetNodesForTree" IsComposable="true">
    <Parameter Name="RootID" Parameter="rootID" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.GetNodesIDsForTree" Method="GetNodesIDsForTree" IsComposable="true">
    <Parameter Name="RootID" Parameter="rootID" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetNodesIDsForTreeResult">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>